// flow-typed signature: 1146da5206028f040a47a9391e5c3bf5
// flow-typed version: <<STUB>>/gatsby-remark-vscode_v^3.2.1/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-vscode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-vscode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-vscode/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/lib/vscode/colorThemeData' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/lib/vscode/modes' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/cacheUtils' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/createCodeNodeRegistry' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/createGetRegistry' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/factory/css' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/factory/html' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/getPossibleThemes' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/graphql/createSchemaCustomization' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/graphql/getCodeBlockDataFromRegistry' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/graphql/getCodeSpanDataFromRegistry' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/graphql/getThemes' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/graphql/highlight' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/graphql/parseThemeCondition' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/graphql/stylesheet' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/host' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/parseCodeFenceInfo' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/parseCodeSpanInfo' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/processExtension' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/registerCodeNode' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/renderers/createWriter' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/renderers/css' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/renderers/html' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/setup' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/storeUtils' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/themeUtils' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/tokenizeWithTheme' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/transformers/diffLineTransformer' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/transformers/getTransformedLines' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/transformers/highlightDirectiveLineTransformer' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/transformers/highlightMetaTransformer' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/transformers' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/transformers/lineNumberTransformer' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/transformers/transformerUtils' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/utils' {
  declare module.exports: any;
}

declare module 'gatsby-remark-vscode/src/validateOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-vscode/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/gatsby-node'>;
}
declare module 'gatsby-remark-vscode/index' {
  declare module.exports: $Exports<'gatsby-remark-vscode'>;
}
declare module 'gatsby-remark-vscode/index.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode'>;
}
declare module 'gatsby-remark-vscode/lib/vscode/colorThemeData.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/lib/vscode/colorThemeData'>;
}
declare module 'gatsby-remark-vscode/lib/vscode/modes.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/lib/vscode/modes'>;
}
declare module 'gatsby-remark-vscode/src/cacheUtils.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/cacheUtils'>;
}
declare module 'gatsby-remark-vscode/src/createCodeNodeRegistry.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/createCodeNodeRegistry'>;
}
declare module 'gatsby-remark-vscode/src/createGetRegistry.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/createGetRegistry'>;
}
declare module 'gatsby-remark-vscode/src/factory/css.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/factory/css'>;
}
declare module 'gatsby-remark-vscode/src/factory/html.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/factory/html'>;
}
declare module 'gatsby-remark-vscode/src/getPossibleThemes.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/getPossibleThemes'>;
}
declare module 'gatsby-remark-vscode/src/graphql/createSchemaCustomization.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/graphql/createSchemaCustomization'>;
}
declare module 'gatsby-remark-vscode/src/graphql/getCodeBlockDataFromRegistry.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/graphql/getCodeBlockDataFromRegistry'>;
}
declare module 'gatsby-remark-vscode/src/graphql/getCodeSpanDataFromRegistry.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/graphql/getCodeSpanDataFromRegistry'>;
}
declare module 'gatsby-remark-vscode/src/graphql/getThemes.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/graphql/getThemes'>;
}
declare module 'gatsby-remark-vscode/src/graphql/highlight.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/graphql/highlight'>;
}
declare module 'gatsby-remark-vscode/src/graphql/parseThemeCondition.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/graphql/parseThemeCondition'>;
}
declare module 'gatsby-remark-vscode/src/graphql/stylesheet.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/graphql/stylesheet'>;
}
declare module 'gatsby-remark-vscode/src/host.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/host'>;
}
declare module 'gatsby-remark-vscode/src/index' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src'>;
}
declare module 'gatsby-remark-vscode/src/index.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src'>;
}
declare module 'gatsby-remark-vscode/src/parseCodeFenceInfo.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/parseCodeFenceInfo'>;
}
declare module 'gatsby-remark-vscode/src/parseCodeSpanInfo.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/parseCodeSpanInfo'>;
}
declare module 'gatsby-remark-vscode/src/processExtension.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/processExtension'>;
}
declare module 'gatsby-remark-vscode/src/registerCodeNode.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/registerCodeNode'>;
}
declare module 'gatsby-remark-vscode/src/renderers/createWriter.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/renderers/createWriter'>;
}
declare module 'gatsby-remark-vscode/src/renderers/css.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/renderers/css'>;
}
declare module 'gatsby-remark-vscode/src/renderers/html.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/renderers/html'>;
}
declare module 'gatsby-remark-vscode/src/setup.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/setup'>;
}
declare module 'gatsby-remark-vscode/src/storeUtils.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/storeUtils'>;
}
declare module 'gatsby-remark-vscode/src/themeUtils.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/themeUtils'>;
}
declare module 'gatsby-remark-vscode/src/tokenizeWithTheme.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/tokenizeWithTheme'>;
}
declare module 'gatsby-remark-vscode/src/transformers/diffLineTransformer.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers/diffLineTransformer'>;
}
declare module 'gatsby-remark-vscode/src/transformers/getTransformedLines.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers/getTransformedLines'>;
}
declare module 'gatsby-remark-vscode/src/transformers/highlightDirectiveLineTransformer.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers/highlightDirectiveLineTransformer'>;
}
declare module 'gatsby-remark-vscode/src/transformers/highlightMetaTransformer.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers/highlightMetaTransformer'>;
}
declare module 'gatsby-remark-vscode/src/transformers/index' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers'>;
}
declare module 'gatsby-remark-vscode/src/transformers/index.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers'>;
}
declare module 'gatsby-remark-vscode/src/transformers/lineNumberTransformer.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers/lineNumberTransformer'>;
}
declare module 'gatsby-remark-vscode/src/transformers/transformerUtils.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/transformers/transformerUtils'>;
}
declare module 'gatsby-remark-vscode/src/utils.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/utils'>;
}
declare module 'gatsby-remark-vscode/src/validateOptions.js' {
  declare module.exports: $Exports<'gatsby-remark-vscode/src/validateOptions'>;
}
declare module 'gatsby-remark-vscode/styles.css' {
  declare module.exports: $Exports<'gatsby-remark-vscode/styles.css'>;
}
